Adição de ChatBot e Mensagem de Boas Vindas
victoricoma/front-helpr pull request #29
Opened 2022-08-31 20:47 UTC by fabreduarte

- [ ]  Adição de ChatBot com respostas para Mensagens de Boas vindas.

2022-08-31 20:49 UTC, fabreduarte commented
Adição de ChatBot na página de Login.
Arquivos alterados
- [ ] Style.scss ( estilização do chatbot)
- [ ] index.html (adição de script chatbot)
- [ ] login (adição do component do chatbot)
- [ ] login.module (adição da importação do chatbot)

2022-08-31 21:00 UTC, brendamelodev commented on src/styles.scss
Cuidado ao indentar o arquivo que está trabalhando para a alteração não subscrever a alteração de outra task.

2022-08-31 21:00 UTC, brendamelodev commented on src/styles.scss
> +html,
Cuidado ao indentar o arquivo que está trabalhando para a alteração não subscrever a alteração de outra task.

2022-08-31 21:01 UTC, brendamelodev commented on src/styles.scss
Cuidado ao indentar o arquivo que está trabalhando para a alteração não subscrever a alteração de outra task.
Obs.: linha 25 à 28.

2022-08-31 21:04 UTC, brendamelodev approved these changes
No arquivo src/styles.scss, houve uma indentação do arquivo trabalhado nas linhas 11 à 13 e 25 à 28. Observar se a alteração não vai subscrever nenhuma outra já feita.

2022-09-01 00:22 UTC, F-Gabriel-Braga approved these changes
Aprovado. Obs: cuidado em manter o código organizado e indentado.

2022-09-01 01:50 UTC, victoricoma requested changes
Existem conflitos na linha de versão tem de corrigir

2022-09-01 12:23 UTC, closed without merging